esphome:
  name: d1mini-display
  platform: ESP8266
  board: d1_mini

# Enable logging
logger:

api:
  encryption:
    key: !secret api_encryption_key

time:
  - platform: homeassistant
    id: esptime
  
text_sensor:
  - platform: homeassistant
    name: "Flight Callsign"
    entity_id: sensor.opensky_callsigns
    id: flight_callsign
    internal: true
#    internal: true
#homeassistant.event:
#      event: opensky_event


font:
  - file: 'slkscr.ttf'
    id: font1
    size: 18

  - file: 'BebasNeue-Regular.ttf'
    id: font2
    size: 36

  - file: 'arial.ttf'
    id: font3
    size: 19

  - file: "dealer.ttf"
    id: bigFont
    size: 30
  - file: "arial.ttf"
    id: smallFont
    size: 12
  - file: 'materialdesignicons-webfont.ttf'
    id: icon
    size: 30
    glyphs:
      - "\U000F001D" # mdi-airplane
    
i2c:
  sda: D5
  scl: D2
  scan: false




display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    reset_pin: D0
    address: 0x3C
    rotation: 180°
    contrast: 50%
    lambda: |-
          it.print(64, 15, id(icon), TextAlign::CENTER, "\U000F001D"); 
          it.printf(64, 51, id(bigFont), TextAlign::CENTER, "%s", id(flight_callsign).state.c_str());

ota:
  password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "D1Mini-Display Fallback Hotspot"
    password: !secret ap_password

captive_portal:
